ci: set up ci
hack-as-a-service/docs pull request #3
Opened 2021-06-03 23:23 UTC by jasonappah

This is going to have to change if we switch to mdbook, but this works for now. I can't remember whether we decided on Nextra or mdBook

2021-06-30 17:35 UTC, anirudhb requested changes

2021-06-30 17:35 UTC, anirudhb commented on .github/workflows/ci.yml
> +          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
`- uses: Swatinem/rust-cache@v1` after the checkout works better

2021-06-30 17:35 UTC, anirudhb commented on .github/workflows/ci.yml
> +      - run: cargo install mdbook
Maybe download the binary release to save time

2021-07-01 18:50 UTC, jasonappah commented on .github/workflows/ci.yml
> +          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
resolving since we switched to getting binaries from github

2021-07-01 19:13 UTC, anirudhb approved these changes

2021-07-01 19:13 UTC, merged